name: Deploy to Droplet

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to Droplet
      run: |
        ssh -i ~/.ssh/id_ed25519 root@${{ secrets.DROPLET_IP }} << 'EOF'
          cd ~/My-App
          git pull origin main
          docker-compose down
          docker-compose up --build -d
        EOF
